baseURL = "https://allanhung.github.io/" 
languageCode = "en-us"  
title = "Blog On Github"  
theme = "github-style"  
googleAnalytics = ""  
publishDir = "allanhung.github.io"

[params]
  author = "allanhung"
  description = "Blog on Github"
  github = "allanhung"
  email = "hung.allan@gmail.com"
  utterances = "allanhung/allanhung.github.io"

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"
