baseURL = "https://allanhung.github.io/" 
languageCode = "en-us"  
title = "Blog On Github"  
theme = "github-style"  
googleAnalytics = ""  
publishDir = "allanhung.github.io"

[menu]
	[[menu.main]]
		name = "Home"
		identifier = "home"
		url = "/"

	[[menu.main]]
		name = "Tags"
		identifier = "tags"
		url = "tags/"

	[[menu.main]]
		name = "Categories"
		identifier = "categories"
		url = "categories/"

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"
